# Generated by Django 4.2.3 on 2023-12-07 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=200)),
                ('patient', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(upload_to='user_profile/')),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.IntegerField(max_length=6)),
                ('UserType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.tag')),
            ],
        ),
    ]
