# Generated by Django 4.2.3 on 2023-12-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='doctor',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='patient',
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
